const Constants = {
  PageUrlPatterns: {
    NoUpwork: "NoUpwork",
    SignUp: "/nx/signup/",
    SignUpDest: "/nx/signup/?dest=home",
    CreateProfile: "/nx/create-profile/",
    Welcome: "/nx/create-profile/welcome",
    Experience: "/nx/create-profile/experience",
    Goal: "/nx/create-profile/goal",
    WorkPreference: "/nx/create-profile/work-preference",
    ResumeImport: "/nx/create-profile/resume-import",
    Title: "/nx/create-profile/title",
    Employeement: "/nx/create-profile/employment",
    Education: "/nx/create-profile/education",
    Languages: "/nx/create-profile/languages",
    Certificate: "/nx/create-profile/certification",
    Skills: "/nx/create-profile/skills",
    Overview: "/nx/create-profile/overview",
    Categories: "/nx/create-profile/categories",
    Rate: "/nx/create-profile/rate",
    Location: "/nx/create-profile/location",
    Submit: "submit",
    Finish: "finish",
  },
  BtnClassNames: {
    getStart: 'air3-btn air3-btn-primary mr-7',
    skip: 'air3-btn air3-btn-link air3-wizard-skip-link-btn',
  },
  Controls: {
    inputFirstName: 'input[id="first-name-input"][type="text"]',
    inputLastName: 'input[id="last-name-input"][type="text"]',
    inputPassword: 'input[id="password-input"][type="password"]',
    inputEmail: 'input[id="redesigned-input-email"][type="email"]',
    pVerifingEmail: 'p[id="submit-form-loader"]',
    spanCountry: 'span[class="flex-1 ellipsis"]',
    comboCountry: 'div[data-test="dropdown-toggle"][aria-expanded="false"]',
    inputCountrySearch: 'input[type="search"][role="combobox"]',
    liCountryFirst: 'li[role="option"]',
    inputAgreeTerm: 'input[id="checkbox-terms"][type="checkbox"]',
    btnSignUp: 'button[id="button-submit-form"][class="up-btn up-btn-primary up-btn-block mt-10 mt-md-20 mb-20"]',
    btnCookieAccept: 'button[id="onetrust-accept-btn-handler"]',
    radioSignUpByLancer: 'input[type="radio"][aria-labelledby="button-box-4"][class="up-button-box-input"][value="work"]',
    btnUploadResume: 'button[type="button"][data-qa="resume-upload-btn-mobile"][class="mb-3 air3-btn air3-btn-secondary d-none d-md-block"]',
    btnResumeChoose: 'a[class="up-n-link"]',
    btnResumeRemove: 'button[data-qa="resume-remove-btn"][class="air3-btn air3-btn-link air3-btn-circle"]',
    btnResumeContinue: 'button:not([disabled="disabled"])[data-qa="resume-upload-continue-btn"]',
    inputTitle: 'input[aria-required="true"][type="text"][aria-labelledby="title-label"][class="air3-input form-control"]',
    ulLanguage: 'ul[aria-labelledby="dropdown-label-english"][role="listbox"][data-test="menu"]',
    comboLanguage:'div[data-test="dropdown-toggle"][aria-expanded="false"]',
    listSkills: 'div[aria-labelledby="token-container-label"][class="token-container"]',
    inputSkills: 'input[aria-labelledby="skills-input"][type="search"]',
    ulSkillsSearch: 'ul[aria-labelledby="skills-input"]',
    btnCategory: 'button:not([aria-disabled="true"])[data-qa="category-add-btn"][role="button"]',
    inputHourly: 'input[type="text"][data-ev-label="currency_input"][data-test="currency-input"][class="air3-input"]',
    btnNext: 'button[data-test="next-button"][type="button"][class="air3-btn air3-btn-primary"]',
    btnApplyAsLancer: 'button[data-qa="btn-apply"][type="button"][class="up-btn up-btn-primary width-md up-btn-block"]',
    btnSubmit: 'button[data-qa="submit-profile-top-btn"][class="submit-profile-top-btn air3-btn air3-btn-primary width-md m-0"]',
    btnBrowseJob: 'a[class="up-n-link air3-btn air3-btn-primary"]',
    txtOverView: 'textarea[aria-labelledby="overview-label"][aria-describedby="overview-counter"]',
    inputPhoneNumber: 'input[type="tel"][inputmode="numeric"]',
    inputZipCode: 'input[data-qa="zip"][aria-labelledby="postal-code-label"]',
    inputStreetAddress: 'input[aria-labelledby="street-label"][type="text"]',
    inputCity: 'input[aria-labelledby="city-label"][type="search"]',
    inputCityOther: 'input[aria-labelledby="state-label"][type="text"]',
    liCityFirst: 'li[role="option"][class="is-uncheckable air3-menu-item"]',
  },
  Ids: {
    firstName: "firstName",
    lastName: "lastName",
    country: "country",
    address: "address",
    phoneNumber: "phoneNumber",
    city: "city",
    zipCode: "zipCode",
    title: "title",
    overview: "overview",
    skills: "skills",
    noSkill: "noSkill",
    skillsUse: "skillsUse",
    resumeImportState: "resumeImportState",
    languageComboState: "languageComboState",
    hourlyInputState: "hourlyInputState",
    skillCountState: "skillCountState",
    isExit: "isExit"
  }
}


export default Constants;